/*
 * Project Euler - Problem 002
 * Even Fibonacci Numbers
 * https://projecteuler.net/problem=2
 *
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * Find the sum of the even-valued terms whose values do not exceed four million.
 *
 * Author: 0x4r35
 * Language: C
 */

#include <stdio.h>

int main() {
    long sum = 0;
    int a = 1, b = 2;

    while (b <= 4000000) {
        if (b % 2 == 0) {
            sum += b;
        }
        int temp = a + b;
        a = b;
        b = temp;
    }

    printf("Problem 002: Sum of even Fibonacci numbers <= 4,000,000 = %ld\n", sum);
    return 0;
}
